name: MeowRoguelike
main: cn.miranda.MeowRoguelike.MeowRoguelike
version: 0.1.2
author: Miranda
description: 猫与地下城/勇者斗恶猫
softdepend: [ MeowCraft, WorldEdit, Multiverse-Core ]
load: POSTWORLD
api-version: 1.15

commands:
  rlroom:
    description: 房间管理与迷宫生成
    usage: /rlroom save|load|list|remove|create
    permissions: rl.*